env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archives:
  - id: binary
    format: binary
    builds:
    - binary-build
  - id: zip
    format: zip
    builds:
    - lambda-build
    files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Version }}_lambda"
builds:
  - id: binary-build
    binary: cloud-key-rotator
    main: ./cmd/
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/ovotech/cloud-key-rotator/pkg/build.Version={{.Version}}
      - -X github.com/ovotech/cloud-key-rotator/pkg/build.Commit={{.ShortCommit}}
      - -X github.com/ovotech/cloud-key-rotator/pkg/build.Date={{.Date}}
      - -X github.com/ovotech/cloud-key-rotator/pkg/build.OsArch={{.Os}}/{{.Arch}}
  - id: lambda-build
    binary: cloud-key-rotator-lambda
    main: ./cmd/
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/ovotech/cloud-key-rotator/pkg/build.Version={{.Version}}
      - -X github.com/ovotech/cloud-key-rotator/pkg/build.Commit={{.ShortCommit}}
      - -X github.com/ovotech/cloud-key-rotator/pkg/build.Date={{.Date}}
      - -X github.com/ovotech/cloud-key-rotator/pkg/build.OsArch={{.Os}}/{{.Arch}}
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - cloud-key-rotator
    image_templates:
    - "ovotech/cloud-key-rotator:{{ .Tag }}"
    - "ovotech/cloud-key-rotator:v{{ .Major }}"
    - "ovotech/cloud-key-rotator:v{{ .Major }}.{{ .Minor }}"
    - "ovotech/cloud-key-rotator:latest"

