env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archives:
  - id: binary
    format: binary
    builds:
    - binary-build
  - id: zip
    format: zip
    builds:
    - lambda-build
    files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Version }}_lambda"
builds:
  - id: binary-build
    binary: cloud-key-rotator
    main: ./cmd/
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/ovotech/cloud-key-rotator/cmd/cobra.version={{.Version}}
      - -X github.com/ovotech/cloud-key-rotator/cmd/cobra.commit={{.ShortCommit}}
      - -X github.com/ovotech/cloud-key-rotator/cmd/cobra.date={{.Date}}
      - -X github.com/ovotech/cloud-key-rotator/cmd/cobra.osArch={{.Os}}/{{.Arch}}
  - id: lambda-build
    binary: cloud-key-rotator
    main: ./cmd/
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
