env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archives:
  - id: binary
    format: binary
    builds:
    - binary-build
  - id: zip
    format: zip
    builds:
    - lambda-build
    files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Version }}_lambda"
builds:
  - id: binary-build
    binary: cloud-key-rotator
    main: ./cmd/
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - id: lambda-build
    binary: cloud-key-rotator
    main: ./cmd/
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
